(source gnu)
(source org)
(source melpa)
(source marmalade)

(depends-on "cask")
(depends-on "dash")
(depends-on "s")
(depends-on "go-mode")
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "jedi")
(depends-on "org")
(depends-on "projectile")
(depends-on "web-mode")
